// Generated by CoffeeScript 1.3.3
(function() {
  var qs, request;

  request = require('request');

  qs = require('querystring');

  exports.app = function(config) {
    var accUrl, appId, appSecret, authUrl, callbackUrl, reqUrl, root;
    root = 'https://vimeo.com/api/rest/v2?format=json';
    reqUrl = 'https://vimeo.com/oauth/request_token';
    authUrl = 'https://vimeo.com/oauth/authorize?oauth_token=';
    accUrl = 'https://vimeo.com/oauth/access_token';
    callbackUrl = config.CALLBACK_URL;
    appId = config.APP_ID;
    appSecret = config.APP_SECRET;
    return {
      requestToken: function(callback) {
        var params, url;
        params = {
          callback: callbackUrl,
          consumer_key: appId,
          consumer_secret: appSecret
        };
        url = reqUrl;
        return request.post({
          url: url,
          oauth: params
        }, function(err, res, body) {
          body = qs.parse(body);
          body.redirect = authUrl + body.oauth_token;
          return callback(body);
        });
      },
      getAccToken: function(params, callback) {
        params.consumer_key = appId;
        params.consumer_secret = appSecret;
        return request.post({
          url: accUrl,
          oauth: params
        }, function(err, res, body) {
          body = qs.parse(body);
          console.log(body);
          return callback(body);
        });
      },
      getUserInfo: function(params, callback) {
        params.consumer_key = appId;
        params.consumer_secret = appSecret;
        console.log(params);
        return request.post({
          url: root + '&method=vimeo.people.getInfo',
          oauth: params
        }, function(err, res, body) {
          body = JSON.parse(body);
          return callback(body);
        });
      },
      getAllVideos: function(params, callback) {
        params.consumer_key = appId;
        params.consumer_secret = appSecret;
        return request.post({
          url: root + '&method=vimeo.videos.getAll',
          oauth: params
        }, function(err, res, body) {
          body = JSON.parse(body);
          return callback(body);
        });
      },
      getThumbnailUrls: function(params, id, callback) {
        params.consumer_key = appId;
        params.consumer_secret = appSecret;
        return request.post({
          url: root + '&method=vimeo.videos.getThumbnailUrls&video_id=' + id,
          oauth: params
        }, function(err, res, body) {
          body = JSON.parse(body);
          return callback(body);
        });
      }
    };
  };

}).call(this);
